scoreboard objectives add fallen_hero_loot dummy fallen_hero_loot
scoreboard players random @s fallen_hero_loot 0 184
execute @s[scores={fallen_hero_loot=0}] ~ ~ ~ structure load protection:protection_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=1}] ~ ~ ~ structure load protection:protection_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=2}] ~ ~ ~ structure load protection:protection_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=3}] ~ ~ ~ structure load protection:protection_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=4}] ~ ~ ~ structure load protection:protection_9 ~ ~ ~
execute @s[scores={fallen_hero_loot=5}] ~ ~ ~ structure load fire_protection:fire_protection_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=6}] ~ ~ ~ structure load fire_protection:fire_protection_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=7}] ~ ~ ~ structure load fire_protection:fire_protection_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=8}] ~ ~ ~ structure load fire_protection:fire_protection_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=9}] ~ ~ ~ structure load fire_protection:fire_protection_9 ~ ~ ~
execute @s[scores={fallen_hero_loot=10}] ~ ~ ~ structure load feather_falling:feather_falling_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=11}] ~ ~ ~ structure load feather_falling:feather_falling_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=12}] ~ ~ ~ structure load feather_falling:feather_falling_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=13}] ~ ~ ~ structure load feather_falling:feather_falling_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=14}] ~ ~ ~ structure load feather_falling:feather_falling_9 ~ ~ ~
execute @s[scores={fallen_hero_loot=15}] ~ ~ ~ structure load blast_protection:blast_protection_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=16}] ~ ~ ~ structure load blast_protection:blast_protection_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=17}] ~ ~ ~ structure load blast_protection:blast_protection_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=18}] ~ ~ ~ structure load blast_protection:blast_protection_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=19}] ~ ~ ~ structure load blast_protection:blast_protection_9 ~ ~ ~
execute @s[scores={fallen_hero_loot=20}] ~ ~ ~ structure load projectile_protection:projectile_protection_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=21}] ~ ~ ~ structure load projectile_protection:projectile_protection_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=22}] ~ ~ ~ structure load projectile_protection:projectile_protection_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=23}] ~ ~ ~ structure load projectile_protection:projectile_protection_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=24}] ~ ~ ~ structure load projectile_protection:projectile_protection_9 ~ ~ ~
execute @s[scores={fallen_hero_loot=25}] ~ ~ ~ structure load thorns:thorns_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=26}] ~ ~ ~ structure load thorns:thorns_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=27}] ~ ~ ~ structure load thorns:thorns_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=28}] ~ ~ ~ structure load thorns:thorns_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=29}] ~ ~ ~ structure load thorns:thorns_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=30}] ~ ~ ~ structure load respiration:respiration_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=31}] ~ ~ ~ structure load respiration:respiration_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=32}] ~ ~ ~ structure load respiration:respiration_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=33}] ~ ~ ~ structure load respiration:respiration_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=34}] ~ ~ ~ structure load respiration:respiration_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=35}] ~ ~ ~ structure load depth_strider:depth_strider_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=36}] ~ ~ ~ structure load depth_strider:depth_strider_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=37}] ~ ~ ~ structure load depth_strider:depth_strider_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=38}] ~ ~ ~ structure load depth_strider:depth_strider_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=39}] ~ ~ ~ structure load depth_strider:depth_strider_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=40}] ~ ~ ~ structure load aqua_affinity:aqua_affinity_2 ~ ~ ~
execute @s[scores={fallen_hero_loot=41}] ~ ~ ~ structure load aqua_affinity:aqua_affinity_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=42}] ~ ~ ~ structure load aqua_affinity:aqua_affinity_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=43}] ~ ~ ~ structure load aqua_affinity:aqua_affinity_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=44}] ~ ~ ~ structure load aqua_affinity:aqua_affinity_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=45}] ~ ~ ~ structure load sharpness:sharpness_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=46}] ~ ~ ~ structure load sharpness:sharpness_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=47}] ~ ~ ~ structure load sharpness:sharpness_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=48}] ~ ~ ~ structure load sharpness:sharpness_9 ~ ~ ~
execute @s[scores={fallen_hero_loot=49}] ~ ~ ~ structure load sharpness:sharpness_10 ~ ~ ~
execute @s[scores={fallen_hero_loot=50}] ~ ~ ~ structure load smite:smite_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=51}] ~ ~ ~ structure load smite:smite_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=52}] ~ ~ ~ structure load smite:smite_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=53}] ~ ~ ~ structure load smite:smite_9 ~ ~ ~
execute @s[scores={fallen_hero_loot=54}] ~ ~ ~ structure load smite:smite_10 ~ ~ ~
execute @s[scores={fallen_hero_loot=55}] ~ ~ ~ structure load bane_of_arthropods:bane_of_arthropods_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=56}] ~ ~ ~ structure load bane_of_arthropods:bane_of_arthropods_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=57}] ~ ~ ~ structure load bane_of_arthropods:bane_of_arthropods_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=58}] ~ ~ ~ structure load bane_of_arthropods:bane_of_arthropods_9 ~ ~ ~
execute @s[scores={fallen_hero_loot=59}] ~ ~ ~ structure load bane_of_arthropods:bane_of_arthropods_10 ~ ~ ~
execute @s[scores={fallen_hero_loot=60}] ~ ~ ~ structure load knockback:knockback_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=61}] ~ ~ ~ structure load knockback:knockback_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=62}] ~ ~ ~ structure load knockback:knockback_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=63}] ~ ~ ~ structure load knockback:knockback_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=64}] ~ ~ ~ structure load knockback:knockback_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=65}] ~ ~ ~ structure load fire_aspect:fire_aspect_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=66}] ~ ~ ~ structure load fire_aspect:fire_aspect_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=67}] ~ ~ ~ structure load fire_aspect:fire_aspect_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=68}] ~ ~ ~ structure load fire_aspect:fire_aspect_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=69}] ~ ~ ~ structure load fire_aspect:fire_aspect_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=70}] ~ ~ ~ structure load looting:looting_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=71}] ~ ~ ~ structure load looting:looting_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=72}] ~ ~ ~ structure load looting:looting_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=73}] ~ ~ ~ structure load looting:looting_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=74}] ~ ~ ~ structure load looting:looting_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=75}] ~ ~ ~ structure load efficiency:efficiency_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=76}] ~ ~ ~ structure load efficiency:efficiency_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=77}] ~ ~ ~ structure load efficiency:efficiency_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=78}] ~ ~ ~ structure load efficiency:efficiency_9 ~ ~ ~
execute @s[scores={fallen_hero_loot=79}] ~ ~ ~ structure load efficiency:efficiency_10 ~ ~ ~
execute @s[scores={fallen_hero_loot=80}] ~ ~ ~ structure load silk_touch:silk_touch_2 ~ ~ ~
execute @s[scores={fallen_hero_loot=81}] ~ ~ ~ structure load silk_touch:silk_touch_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=82}] ~ ~ ~ structure load silk_touch:silk_touch_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=83}] ~ ~ ~ structure load silk_touch:silk_touch_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=84}] ~ ~ ~ structure load silk_touch:silk_touch_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=85}] ~ ~ ~ structure load unbreaking:unbreaking_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=86}] ~ ~ ~ structure load unbreaking:unbreaking_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=87}] ~ ~ ~ structure load unbreaking:unbreaking_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=88}] ~ ~ ~ structure load unbreaking:unbreaking_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=89}] ~ ~ ~ structure load unbreaking:unbreaking_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=90}] ~ ~ ~ structure load fortune:fortune_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=91}] ~ ~ ~ structure load fortune:fortune_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=92}] ~ ~ ~ structure load fortune:fortune_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=93}] ~ ~ ~ structure load fortune:fortune_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=94}] ~ ~ ~ structure load fortune:fortune_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=95}] ~ ~ ~ structure load power:power_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=96}] ~ ~ ~ structure load power:power_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=97}] ~ ~ ~ structure load power:power_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=98}] ~ ~ ~ structure load power:power_9 ~ ~ ~
execute @s[scores={fallen_hero_loot=99}] ~ ~ ~ structure load power:power_10 ~ ~ ~
execute @s[scores={fallen_hero_loot=100}] ~ ~ ~ structure load punch:punch_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=101}] ~ ~ ~ structure load punch:punch_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=102}] ~ ~ ~ structure load punch:punch_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=103}] ~ ~ ~ structure load punch:punch_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=104}] ~ ~ ~ structure load punch:punch_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=105}] ~ ~ ~ structure load flame:flame_2 ~ ~ ~
execute @s[scores={fallen_hero_loot=106}] ~ ~ ~ structure load flame:flame_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=107}] ~ ~ ~ structure load flame:flame_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=108}] ~ ~ ~ structure load flame:flame_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=109}] ~ ~ ~ structure load flame:flame_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=110}] ~ ~ ~ structure load infinity:infinity_2 ~ ~ ~
execute @s[scores={fallen_hero_loot=111}] ~ ~ ~ structure load infinity:infinity_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=112}] ~ ~ ~ structure load infinity:infinity_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=113}] ~ ~ ~ structure load infinity:infinity_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=114}] ~ ~ ~ structure load infinity:infinity_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=115}] ~ ~ ~ structure load luck_of_the_sea:luck_of_the_sea_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=116}] ~ ~ ~ structure load luck_of_the_sea:luck_of_the_sea_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=117}] ~ ~ ~ structure load luck_of_the_sea:luck_of_the_sea_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=118}] ~ ~ ~ structure load luck_of_the_sea:luck_of_the_sea_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=119}] ~ ~ ~ structure load luck_of_the_sea:luck_of_the_sea_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=120}] ~ ~ ~ structure load lure:lure_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=121}] ~ ~ ~ structure load lure:lure_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=122}] ~ ~ ~ structure load lure:lure_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=123}] ~ ~ ~ structure load lure:lure_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=124}] ~ ~ ~ structure load lure:lure_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=125}] ~ ~ ~ structure load frost_walker:frost_walker_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=126}] ~ ~ ~ structure load frost_walker:frost_walker_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=127}] ~ ~ ~ structure load frost_walker:frost_walker_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=128}] ~ ~ ~ structure load frost_walker:frost_walker_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=129}] ~ ~ ~ structure load frost_walker:frost_walker_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=130}] ~ ~ ~ structure load mending:mending_2 ~ ~ ~
execute @s[scores={fallen_hero_loot=131}] ~ ~ ~ structure load mending:mending_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=132}] ~ ~ ~ structure load mending:mending_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=133}] ~ ~ ~ structure load mending:mending_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=134}] ~ ~ ~ structure load mending:mending_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=135}] ~ ~ ~ structure load binding:binding_2 ~ ~ ~
execute @s[scores={fallen_hero_loot=136}] ~ ~ ~ structure load binding:binding_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=137}] ~ ~ ~ structure load binding:binding_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=138}] ~ ~ ~ structure load binding:binding_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=139}] ~ ~ ~ structure load binding:binding_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=140}] ~ ~ ~ structure load vanishing:vanishing_2 ~ ~ ~
execute @s[scores={fallen_hero_loot=141}] ~ ~ ~ structure load vanishing:vanishing_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=142}] ~ ~ ~ structure load vanishing:vanishing_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=143}] ~ ~ ~ structure load vanishing:vanishing_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=144}] ~ ~ ~ structure load vanishing:vanishing_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=145}] ~ ~ ~ structure load impaling:impaling_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=146}] ~ ~ ~ structure load impaling:impaling_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=147}] ~ ~ ~ structure load impaling:impaling_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=148}] ~ ~ ~ structure load impaling:impaling_9 ~ ~ ~
execute @s[scores={fallen_hero_loot=149}] ~ ~ ~ structure load impaling:impaling_10 ~ ~ ~
execute @s[scores={fallen_hero_loot=150}] ~ ~ ~ structure load riptide:riptide_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=151}] ~ ~ ~ structure load riptide:riptide_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=152}] ~ ~ ~ structure load riptide:riptide_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=153}] ~ ~ ~ structure load riptide:riptide_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=154}] ~ ~ ~ structure load riptide:riptide_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=155}] ~ ~ ~ structure load loyalty:loyalty_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=156}] ~ ~ ~ structure load loyalty:loyalty_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=157}] ~ ~ ~ structure load loyalty:loyalty_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=158}] ~ ~ ~ structure load loyalty:loyalty_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=159}] ~ ~ ~ structure load loyalty:loyalty_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=160}] ~ ~ ~ structure load channeling:channeling_2 ~ ~ ~
execute @s[scores={fallen_hero_loot=161}] ~ ~ ~ structure load channeling:channeling_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=162}] ~ ~ ~ structure load channeling:channeling_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=163}] ~ ~ ~ structure load channeling:channeling_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=164}] ~ ~ ~ structure load channeling:channeling_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=165}] ~ ~ ~ structure load multishot:multishot_2 ~ ~ ~
execute @s[scores={fallen_hero_loot=166}] ~ ~ ~ structure load multishot:multishot_3 ~ ~ ~
execute @s[scores={fallen_hero_loot=167}] ~ ~ ~ structure load multishot:multishot_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=168}] ~ ~ ~ structure load multishot:multishot_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=169}] ~ ~ ~ structure load multishot:multishot_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=170}] ~ ~ ~ structure load piercing:piercing_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=171}] ~ ~ ~ structure load piercing:piercing_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=172}] ~ ~ ~ structure load piercing:piercing_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=173}] ~ ~ ~ structure load piercing:piercing_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=174}] ~ ~ ~ structure load piercing:piercing_9 ~ ~ ~
execute @s[scores={fallen_hero_loot=175}] ~ ~ ~ structure load quick_charge:quick_charge_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=176}] ~ ~ ~ structure load quick_charge:quick_charge_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=177}] ~ ~ ~ structure load quick_charge:quick_charge_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=178}] ~ ~ ~ structure load quick_charge:quick_charge_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=179}] ~ ~ ~ structure load quick_charge:quick_charge_8 ~ ~ ~
execute @s[scores={fallen_hero_loot=180}] ~ ~ ~ structure load soul_speed:soul_speed_4 ~ ~ ~
execute @s[scores={fallen_hero_loot=181}] ~ ~ ~ structure load soul_speed:soul_speed_5 ~ ~ ~
execute @s[scores={fallen_hero_loot=182}] ~ ~ ~ structure load soul_speed:soul_speed_6 ~ ~ ~
execute @s[scores={fallen_hero_loot=183}] ~ ~ ~ structure load soul_speed:soul_speed_7 ~ ~ ~
execute @s[scores={fallen_hero_loot=184}] ~ ~ ~ structure load soul_speed:soul_speed_8 ~ ~ ~